export const categoriesMap = {"category":{"/":{"path":"/category/","map":{"使用指南":{"path":"/category/使用指南/","indexes":[0]},"WEB":{"path":"/category/web/","indexes":[0]},"HTML":{"path":"/category/html/","indexes":[0]},"flume":{"path":"/category/flume/","indexes":[1,2,3,4]},"sink":{"path":"/category/sink/","indexes":[3]},"flume学习":{"path":"/category/flume学习/","indexes":[5]},"vue":{"path":"/category/vue/","indexes":[6,7,8,9,10]},"Git":{"path":"/category/git/","indexes":[11,12]},"git学习":{"path":"/category/git学习/","indexes":[13]},"Linux":{"path":"/category/linux/","indexes":[14]},"MySQL":{"path":"/category/mysql/","indexes":[15]},"webServer":{"path":"/category/webserver/","indexes":[16]},"CacheDatabase":{"path":"/category/cachedatabase/","indexes":[17]},"JavaWeb":{"path":"/category/javaweb/","indexes":[18]},"web学习":{"path":"/category/web学习/","indexes":[19]},"project":{"path":"/category/project/","indexes":[20,21]},"os":{"path":"/category/os/","indexes":[22]}}}},"tag":{"/":{"path":"/tag/","map":{"project.ts":{"path":"/tag/project.ts/","indexes":[23]},"flume":{"path":"/tag/flume/","indexes":[1,2,3,4]},"channel":{"path":"/tag/channel/","indexes":[1]},"guide":{"path":"/tag/guide/","indexes":[2,8]},"sink":{"path":"/tag/sink/","indexes":[3]},"source":{"path":"/tag/source/","indexes":[4]},"vue":{"path":"/tag/vue/","indexes":[6,8]},"core":{"path":"/tag/core/","indexes":[7]},"pinia":{"path":"/tag/pinia/","indexes":[9]},"router":{"path":"/tag/router/","indexes":[10]},"go":{"path":"/tag/go/","indexes":[24]},"Java":{"path":"/tag/java/","indexes":[25]},"git":{"path":"/tag/git/","indexes":[11,12]},"advanced":{"path":"/tag/advanced/","indexes":[11]},"linux":{"path":"/tag/linux/","indexes":[26,14]},"shell":{"path":"/tag/shell/","indexes":[14]},"mysql":{"path":"/tag/mysql/","indexes":[27,15]},"nginx":{"path":"/tag/nginx/","indexes":[28,16]},"redis":{"path":"/tag/redis/","indexes":[29,17]},"JavaWeb":{"path":"/tag/javaweb/","indexes":[18,30]},"基本使用":{"path":"/tag/基本使用/","indexes":[18]},"JavaWeb教程":{"path":"/tag/javaweb教程/","indexes":[19]},"backend":{"path":"/tag/backend/","indexes":[20]},"frontend":{"path":"/tag/frontend/","indexes":[21]},"Springboot":{"path":"/tag/springboot/","indexes":[31]},"dv":{"path":"/tag/dv/","indexes":[32]},"dbs":{"path":"/tag/dbs/","indexes":[33,34]},"os":{"path":"/tag/os/","indexes":[22,35]}}}}};

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept();
  if (__VUE_HMR_RUNTIME__.updateBlogCategory)
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoriesMap);
}

if (import.meta.hot)
  import.meta.hot.accept(({ categoriesMap }) => {
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoriesMap);
  });

